@ShoppingList.API_HostAddress = http://localhost:5082

GET {{ShoppingList.API_HostAddress}}/products/
Accept: application/json

###

POST {{ShoppingList.API_HostAddress}}/products/
Content-Type: application/json

{
  "name": "jajka",
  "shop": "Lidl"
}

###

PUT {{ShoppingList.API_HostAddress}}/products/1
Content-Type: application/json

{
  "name": "jajka",
  "shop": "Lidl",
  "handled": true
}

###

DELETE {{ShoppingList.API_HostAddress}}/products/1
